class SupabaseSecret{
  static const supabaseUrl = 'https://cgkfcarnfiehlkrchfct.supabase.co';
   static const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNna2ZjYXJuZmllaGxrcmNoZmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Nzk2MzUsImV4cCI6MjA2NzA1NTYzNX0.VhgXIj1dt32UZxqv8InIMikEA5UVLWsxnXLntarWN9o';
}